
public enum TOWER_TYPE
{
    // 1단계 0~1, 2단계 2~7, 3단계 8~11
    BLACK_PAWN, WHITE_PAWN, BLACK_KNIGHT, WHITE_KNIGHT, BLACK_ROOK, WHITE_ROOK, BLACK_BISHOP, WHITE_BISHOP,
    BLACK_QUEEN, WHITE_QUEEN, BLACK_KING, WHITE_KING
}

public enum COLOR_TYPE
{
    BLACK, WHITE
}
public enum ROUND_TYPE
{
    ROUND_ONE, ROUND_TWO, ROUND_THREE, ROUND_FOUR, ROUND_FIVE, ROUND_SIX, ROUND_SEVEN, ROUND_EIGHT,
    ROUND_NINE, ROUND_TEN, ROUND_ELEVEN, ROUND_TWELVE, ROUND_THIRTEEN, ROUND_FOURTEEN, ROUND_FIFTEEN
}
public enum SKILL_TYPE
{
    BLACK_KNIGHT_SKILL, WHITE_KNIGHT_SKILL, BLACK_ROOK_SKILL, WHITE_ROOK_SKILL, 
    BLACK_BISHOP_SKILL, WHITE_BISHOP_SKILL, BLACK_QUEEN_SKILL, WHITE_QUEEN_SKILL, BLACK_KING_SKILL, WHITE_KING_SKILL
}



