
public enum TOWER_TYPE
{
    // 1단계 0~1, 2단계 2~7, 3단계 8~11
    BLACK_PAWN, WHITE_PAWN, BLACK_KNIGHT, BLACK_ROOK, BLACK_BISHOP, WHITE_KNIGHT, WHITE_ROOK, WHITE_BISHOP,
    BLACK_QUEEN, BLACK_KING, WHITE_QUEEN, WHITE_KING
}

public enum COLOR_TYPE
{
    BLACK, WHITE
}
public enum ROUND_TYPE
{
    ROUND_ONE, ROUND_TWO, ROUND_THREE, ROUND_FOUR, ROUND_FIVE, ROUND_SIX, ROUND_SEVEN, ROUND_EIGHT,
    ROUND_NINE, ROUND_TEN, ROUND_ELEVEN, ROUND_TWELVE, ROUND_THIRTEEN, ROUND_FOURTEEN, ROUND_FIFTEEN
}



